name: RPi image

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  release:
    types: 
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set execute permissions
        run: chmod +x ./builder/*.sh && chmod +x ./builder/assets/*.sh

      - name: Build image
        run: |
          docker run --privileged --rm -v /dev:/dev -v $(pwd):/builder/repo -e TRAVIS_TAG="${{ github.event.release.tag_name || '' }}" arutofu/img-tool:qemu-update /bin/bash -c "chmod +x /builder/repo/builder/image-build.sh && /builder/repo/builder/image-build.sh"

      - name: Compress image
        run: |
          cd images && sudo chmod -R 777 . 
          TAG_NAME="${{ github.event.release.tag_name || 'no_release_tag' }}"
          zip -9 "image_${TAG_NAME}.zip" *_* && ls -l . && unzip -l "image_${TAG_NAME}.zip"

      - name: Upload image to release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: images/image*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
