name: Build and Release Raspberry Pi Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image
        run: docker build -t drone-image .

      - name: Grant execution permissions to build_image.sh
        run: chmod +x scripts/build_image.sh

      - name: Run build script inside Docker
        run: docker run --rm --privileged -v ${PWD}:/workspace -w /workspace drone-image ./scripts/build_image.sh

      - name: Compress image
        run: zip drone_raspberry_pi_image.zip drone_raspberry_pi_image.img

      - name: Upload image to release
        uses: actions/upload-artifact@v2
        with:
          path: drone_raspberry_pi_image.zip
          name: drone_raspberry_pi_image.zip
