name: Copy Docker Image

on:
  workflow_dispatch:

jobs:
  copy-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Pull Docker image
      run: docker pull sfalexrog/img-tool:qemu-update
      
    - name: Create docker_image directory
      run: mkdir -p docker_image
      
    - name: Save Docker image to tar file
      run: docker save -o docker_image/img-tool_qemu-update.tar sfalexrog/img-tool:qemu-update
      
    - name: Extract Docker image contents
      run: tar -xvf docker_image/img-tool_qemu-update.tar -C docker_image
      
    - name: Remove tar file
      run: rm docker_image/img-tool_qemu-update.tar

    - name: Configure git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        git config --global http.postBuffer 209715200

    - name: Commit and push changes
      run: |
        cd docker_image
        git init
        git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/arutofu/image_builder_v2.git
        git checkout -b CopyDockerImage
        git add .
        git commit -m "Add files from Docker image sfalexrog/img-tool:qemu-update"
        git pull origin CopyDockerImage --rebase
        for i in {1..5}; do git push -u origin CopyDockerImage && break || sleep 15; done
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Remove temporary Docker container
      run: docker rm temp_container
