name: Copy Docker Image

on:
  push:
    branches:
      - CopyDockerImage_copy

jobs:
  copy-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker image
      run: docker pull sfalexrog/img-tool:qemu-update

    - name: Create Docker container
      run: docker create --name temp_container sfalexrog/img-tool:qemu-update

    - name: Export Docker container contents
      run: |
        mkdir -p ./docker_image
        docker export temp_container | tar -C ./docker_image -xvf -

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"

    - name: Commit and push to repository
      run: |
        cd docker_image
        git init
        git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/arutofu/image_builder_v2.git
        git checkout -b CopyDockerImage
        git add .
        git commit -m "Add files from Docker image sfalexrog/img-tool:qemu-update"
        git pull origin CopyDockerImage --rebase
        git push -u origin CopyDockerImage
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Remove temporary Docker container
      run: docker rm temp_container

    - name: Check if Docker image exists in my Docker Hub
      id: image-check
      run: |
        if docker pull arutofu/img-tool:qemu-update; then
          echo "Image already exists."
          echo "image_exists=true" >> $GITHUB_ENV
        else
          echo "Image does not exist."
          echo "image_exists=false" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image to my Docker Hub
      if: env.image_exists == 'false'
      run: |
        docker build -t arutofu/img-tool:qemu-update ./docker_image
        docker push arutofu/img-tool:qemu-update
